# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-12 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
